/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package by.mjc.util;

import org.junit.Test;
import static org.junit.Assert.*;

public class StringUtilsTest {
	
    @Test 
    public void isPositiveNumber_whenPositive_thenTrue() {
        StringUtils classUnderTest = new StringUtils();
        boolean actual = classUnderTest.isPositiveNumber("10");
        boolean expected = true;
        
        assertEquals(expected, actual);
    }
}
